### ISSUE TITLE
Support Redis Sentinel Authentication (SENTINEL_KWARGS)

### ISSUE THREAD

**Issue by K-MTG** [django/channels_redis#300] opened 2022-03-06 18:39 UTC
Current config does not appear to allow me to define `SENTINEL_KWARGS` where I can specify a sentinel password for sentinel authentication. 

This appears to be a limitation with the current version of `airoredis` as support was added in 2.0: https://github.com/aio-libs/aioredis-py/issues/690

**Comment by carltongibson** [comment] 2022-03-07 17:57
Yep, this is a duplicate of #285

**Comment by andriilahuta** [comment] 2022-07-17 22:32
@carltongibson can we reopen this since it's no longer related to #285?

I think we can put _sentinel_kwargs_ here and it should just work:
https://github.com/django/channels_redis/blob/d946ce2875b2a2efe2c4cbfb14107fd7d7a4a551/channels_redis/core.py#L138

**Comment by carltongibson** [comment] 2022-07-18 06:34
@andriilahuta OK, yep. If you want an open a PR with tests for that we can have a look. Thanks. 👍

**Closed** 2022-09-08 18:22 UTC
