### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by antoinebou12** [django/channels_redis#397] opened 2024-08-19 17:00 UTC
```
ERROR 2024-08-19 12:58:28,253 server Exception inside application: unknown command 'BZPOPMIN'
Traceback (most recent call last):
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\routing.py", line 132, in __call__
    return await application(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\antoi\OneDrive\Bureau\Code\ETS\CLUB\ALGOETS\Simulateur\venv\Lib\site-packages\channels\utils.py", line 57, in await_many_dispatch
    await task
redis.exceptions.ResponseError: unknown command 'BZPOPMIN'
```

channels-redis=-=4.2.0
redis=7.4

**Comment by carltongibson** [comment] 2024-08-19 17:26
Duplicate of #203. Please search before opening issues. Upgrade Redis.

**Comment by carltongibson** [comment] 2024-08-19 17:27
Duplicate of #203. Please search before opening issues. Upgrade Redis.

**Closed by carltongibson** 2024-08-19 17:26 UTC

**Comment by antoinebou12** [comment] 2024-08-19 19:24
@carltongibson I found the issue not a issue with redis i got the right version `redis=7.4`
the issue was with my Consumer missing function name and i change to 
`
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
`
