### ISSUE TITLE
Improve sending efficiency for large Groups

### ISSUE THREAD

**Issue by lsapan** [django/channels_redis#62] opened 2017-10-18 16:27 UTC
This is really just the continuation of https://github.com/django/channels/issues/763, as it was determined that the redis channel layer was causing the issue.

At smaller Group sizes (less than 100) it is not really noticeable. Once you get to 200, some messages are occasionally dropped. At around 400+ it becomes very evident and can even approach a 50% failure rate.

I've created a repo to reproduce this issue very easily: https://github.com/lsapan/channels-mass-broadcast

The repo's README explains everything in depth, but here's everything you need to reproduce it:
```
git clone https://github.com/lsapan/channels-mass-broadcast.git
cd channels-mass-broadcast
docker-compose pull
docker-compose up
```

That will start daphne, a worker, redis, etc. Then simply navigate to http://localhost:8000/ in 1-3 unique web browsers and watch the number of messages coming in through the console.

**Comment by andrewgodwin** [comment] 2017-10-18 17:28
Right, it being in groups explains why I've never seen the issue when we put 5,000 req/sec through it because we never use that part.

Group sending right now is not implemented very efficiently, and I suspect this is due to the for-loop style of sending falling down. I'm going to look into better group send mechanisms and see what I can come up with to improve it, though that may have to be part of the ongoing rewrite of asgi_redis to be async for channels 2.

**Comment by andrewgodwin** [comment] 2018-02-02 07:38
Closing as duplicate of #7

**Closed by andrewgodwin** 2018-02-02 07:38 UTC
