### ISSUE TITLE
Test stuck on ARM64

### ISSUE THREAD

**Issue by odidev** [django/channels_redis#304] opened 2022-04-08 09:14 UTC
Hi @[carltongibson](https://github.com/django/channels_redis/commits?author=carltongibson)
I have been working on installing and testing channels-redis package on x86 and arm64 architectures. While testing this package for **arm64** using `python –m tox` the test stuck in the middle. 

```
tests/test_pubsub.py::test_proxied_methods_coroutine_check PASSED [ 46%] 
tests/test_pubsub_sentinel.py::test_send_receive 

```
Please have a look at the test output. It would be really helpful if you could share some pointers on it.

**Test output at arm64:** [gha_test_arm64_channel-redis_with_py38(failed).txt](https://github.com/django/channels_redis/files/8450443/gha_test_arm64_channel-redis_with_py38.failed.txt)

**Comment by carltongibson** [comment] 2022-04-08 09:30
HI @odidev — that's a lot of `apt`... 😅

This line: 

```
2022-04-06T12:38:21.3875574Z ##[error]The operation was canceled.
``

Can you find a reason for that? 

(I'm afraid there's nothing that jumps out.)

**Comment by carltongibson** [comment] 2022-09-02 08:06
Duplicate of #319

**Closed by carltongibson** 2022-09-02 08:06 UTC
