### ISSUE TITLE
Locking exception gets thrown on occasion

### ISSUE THREAD

**Issue by maliesa96** [django/channels_redis#136] opened 2018-11-07 22:09 UTC
I'm using channels for a personal project and every now and then an exception gets thrown regarding locking. It doesn't seem to be caused by any action in particular, it just seems to happen randomly. I can't seem to find a solution. 

I'm using Python 3.7
Traceback:

Exception inside application: 
  File "/Users/Mishari/apollo-env/lib/python3.7/site-packages/channels/sessions.py", line 179, in __call__
    return await self.inner(receive, self.send)
  File "/Users/Mishari/apollo-env/lib/python3.7/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/Users/Mishari/apollo-env/lib/python3.7/site-packages/channels/utils.py", line 59, in await_many_dispatch
    await task
  File "/Users/Mishari/apollo-env/lib/python3.7/site-packages/channels_redis/core.py", line 449, in receive
    assert not self.receive_lock.locked()

freeze:
aioredis==1.2.0
asgiref==2.3.2
async-timeout==2.0.1
attrs==18.2.0
autobahn==18.9.2
Automat==0.7.0
channels==2.1.4
channels-redis==2.3.1
constantly==15.1.0
daphne==2.2.2
Django==2.1.2
hiredis==0.2.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
msgpack==0.5.6
PyHamcrest==1.9.0
pytz==2018.5
six==1.11.0
Twisted==18.9.0
txaio==18.8.1
zope.interface==4.5.0

Thanks in advance

**Comment by andrewgodwin** [comment] 2018-11-08 03:58
I've heard reports of this occasionally from elsewhere, but I need more information to solve this - specifically, I need a way to reliably reproduce it. Without that, there's not much we can do!

**Comment by maliesa96** [comment] 2018-11-08 23:30
I'm thinking to use pdb to see if I can get you some more info. I'll update if i find anything.

**Comment by maliesa96** [comment] 2018-11-09 02:47
So it seems to happen after a websocket disconnects. I got pdb to trigger a breakpoint. I can see that
`self.receive_lock.locked()` evaluates to true when it shouldn't be (I assume that was pretty obvious).

Could this possibly be due to the fact that the websocket was closed abruptly without triggering the disconnect function in the consumer?

**Comment by andrewgodwin** [comment] 2018-11-10 04:53
Maybe - we might be missing a `finally` somewhere that isn't getting triggered on the way out of an abrupt disconnect. That locking code is... complicated.

**Comment by mawkee** [comment] 2018-11-14 21:01
I've stumbled with the exact same problem; The real issue on my case was that a bug caused by my code raised an exception, BEFORE the connection was accepted or closed. So when the exception reached the `finally` code, the assert failed as well, hiding the root cause (the bug on the code).

IMHO, raising an exception on a `finally:` block might be problematic for debugging for these exact reasons

**Comment by kowsari** [comment] 2018-11-14 21:54
I am having the same problem. It seems to occur for me after after day or two on our development server with a few users logging in and disconnecting. Is it recommended to call anything in my     
```
async def disconnect(self, code):
        WandaLogger().CORE.info('Websocket disconnect')

```
If I can somehow recreate the issue I can try to send you the info.

**Comment by andrewgodwin** [comment] 2018-11-26 20:38
It's likely that this is now fixed with the merge of https://github.com/django/channels_redis/pull/140 - anyone able to test?

**Comment by kowsari** [comment] 2018-11-27 14:49
Seems to be fixed for me too!

**Comment by andrewgodwin** [comment] 2018-11-27 17:21
Great, I'll get that fix rolled out in a release soon then.

**Closed by andrewgodwin** 2018-11-27 17:21 UTC
Labels: blocked/user-response
